version: "3.9"

services:
  macos:
    build: .
    container_name: macos

    stdin_open: true
    tty: true
    privileged: true

    devices:
      - /dev/kvm

    ports:
      - "50922:10022"

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - macos_data:/home/arch/OSX

    environment:
      # display
      DISPLAY: ${DISPLAY:-:0.0}

      # serial / config
      GENERATE_UNIQUE: "true"
      MASTER_PLIST_URL: "https://raw.githubusercontent.com/sickcodes/osx-serial-generator/master/config-custom-sonoma.plist"
      SHORTNAME: "sequoia"

      # CPU (igual ao docker run)
      CPU: "Haswell-noTSX"
      CPUID_FLAGS: "kvm=on,vendor=GenuineIntel,+invtsc,vmware-cpuid-freq=on"

      # recursos
      RAM: "8"
      SMP: "4"

      # opcional (mantive o seu)
      EXTRA: "-cpu host"

    dns:
      - 8.8.8.8
      - 1.1.1.1

    restart: unless-stopped

volumes:
  macos_data: